# ChitChat - v${version}
# Welcome to the configuration file.

formats:
  default:
    priority: 2147483647

    channel: '[%player_exp%] '
    channel_tooltip:
      - '<red>%player_name%s <gray>XP'
    channel_click_command: '/msg %player_name% '

    prefix: ''
    prefix_tooltip: []
    prefix_click_command: '[EXECUTE]/ranks'

    name: '<rainbow>%player_name%</rainbow>'
    name_tooltip:
      - '<gray>-=[<gold>✦<gray>]=-  <gray>-=[<yellow>%player_name%<gray>]=-  <gray>-=[<gold>✦<gray>]=-'
      - '<purple>Sent: <white>%player_timestamp%'
    name_click_command: /ranks

    suffix: ' <#22d3ee>» '
    suffix_tooltip: []
    suffix_click_command: ''

    chat: '<white>%message%'
    chat_tooltip: []
    chat_click_command: ''