# ChitChat - v${version}
# Welcome to the configuration file.

formats:
  default:
    priority: 2147483647

    channel: '[%player_exp%] '
    channel_tooltip:
      - '&c%player_name%s &7XP'
    channel_click_command: '/msg %player_name% '

    prefix: ''
    prefix_tooltip: []
    prefix_click_command: '[EXECUTE]/ranks'

    name: '<rainbow>%player_name%</rainbow>'
    name_tooltip:
      - '&7-=[&6✦&7]=-  &7-=[&e%player_name%&7]=-  &7-=[&6✦&7]=-'
      - '&5Sent: &f%player_timestamp%'
    name_click_command: /ranks

    suffix: ' <#22d3ee>» '
    suffix_tooltip: []
    suffix_click_command: ''

    chat: '&f%message%'
    chat_tooltip: []
    chat_click_command: ''